services:
  geth:
    image: ethereum/client-go:latest
    ports:
      - "8545:8545"
      - "30303:30303"
    command: >
      --dev
      --dev.period 5
      --datadir /data
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api eth,web3,personal,net
      --http.corsdomain "*"
      --allow-insecure-unlock
      --verbosity 3
    volumes:
      - geth-data:/data

volumes:
  geth-data: